### ISSUE TITLE
When !say is used, the bot should try to remove the command

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot#18]
It's nicer if the bot will delete the message triggering the command when the bot executes a command such as `!say`, `!meme` or any other command that fires a response wherein the issuer is not a huge requirement.

**Comment by Mirrorbreak** [comment]
Due to lack of ES6, this is impossible

**Comment by SteamingMutt** [comment]
ES6 support added, requires extra start-up command
