### ISSUE TITLE
Bot ceases to function when @ mentioned

### ISSUE THREAD

**Issue by SteamingMutt** [SteamingMutt/DougleyBot#2]
When the bot is @ mentioned, the entire script will crash and the server owner needs to restart the bot.

**Comment by SteamingMutt** [comment]
This error only occurs when the bot is @ mentioned without a command beside the mention.

**Comment by JLBP** [comment]
In JaLBot I removed the following from line 338 to 341 (on the git pull):

        if(msg.content.indexOf(bot.user.mention()) == 0){
            cmdTxt = msg.content.split(" ")[1];
            suffix = msg.content.substring(bot.user.mention().length+cmdTxt.length+2);
        }

and removed + cmdTxt from line 361

			bot.sendMessage(msg.channel, "Invalid command " + cmdTxt);

That prevents the bot from crashing, currently working on a way for the bot to response back with a simple "Hi"

**Comment by SteamingMutt** [comment]
Fixed in 370eca506637da1d892ff84c3a9ec2cba2b4c9a8

**Comment by SteamingMutt** [comment]
The code that will make the bot crash is removed, issue no longer present.
