### ISSUE TITLE
Make !wiki lists less spammy

### ISSUE THREAD

**Issue by Perpetucake** [SteamingMutt/DougleyBot#55]
Simple way to accomplish this would be to build up to 2000 character msgArray's (similar code already located in DougleyBot Kervin ;) ) and send those instead of separating each new line to a new message (creating many many notifications in Discord, and the potential for massive cross-bot command spam).

A better way may be a complete rewrite, possibly with https://www.npmjs.com/package/node-wikipedia which appears to have more features (but less documentation) than wikijs.

**Comment by Perpetucake** [comment]
Tagged enhancement but this is really a rather large flaw IMO as it allows cross-bot spam that could be minimized greatly with a fix.

**Comment by SteamingMutt** [comment]
We could be lazy and just remove `continuation`

**Comment by SteamingMutt** [comment]
Lazily fixed by removing `continuation`
