### ISSUE TITLE
Typing any command that sends an image in private message crashes bot.

### ISSUE THREAD

**Issue by TransactionHF** [SteamingMutt/DougleyBot#73]
Typing any command which is meant to send an image in a private message to the bot instantly causes it to crash. This makes the bot impossible for me to use on my public server without disabling all image commands.

For instance, opening a message with the bot and typing !kappa will crash it. Same with !iff <anything>

**Comment by SteamingMutt** [comment]
Related to message deletion, fixing asap.

**Comment by SteamingMutt** [comment]
Version 1.3.4 fixes crashing when iff and kappa are used, say is being a b*tch and won't work
