### ISSUE TITLE
Discord ID Location

### ISSUE THREAD

**Issue by tohtreb** [SteamingMutt/DougleyBot#88]
Hi there, really enjoying your bot (had it join our server to test with) but I am trying to setup the config file to create our own version of it and I'm hung up on the part where you enter the admin IDs because I can't find where they are.  I checked the FAQ section and found this answer, "That's because you didn't define your Discord ID as a admin, check the config.json file if your ID is defined as a admin." But the problem is that I can't seem to find anywhere that tells me where to find the ID number to put in.  Is there any way you could point me in the right direction to find my Discord ID so I can put it in there?

Thank you!

**Comment by SteamingMutt** [comment]
If you start the bot without ID's or with the default ones, use `!whois <discord-mention>` to get the ID from an user.

**Comment by tohtreb** [comment]
Thank you so much!
