### ISSUE TITLE
Possible upgrade for your use case of csgo-market

### ISSUE THREAD

**Issue by httpNick** [SteamingMutt/DougleyBot#89]
I have added an option to disable strict weapon name mode which will attempt to match the closest name of the weapon passed in, so if users using your bot type 'AK 47' instead of 'AK-47' it will still pick up the name and format it correctly for the request.

To disable strict naming simply use this line:

`csgomarket.strictNameMode = false;`

**Comment by SteamingMutt** [comment]
:+1: Changes implemented in https://github.com/SteamingMutt/WildBeast/commit/4902651c6e1f734d5b49369d8706ee7ed1f315a1
